name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run run-test
          command: npm run generate-report      
        uses: actions/upload-artifact@v4
        with:
      - name: my-artifact
        path: cypres/reports/html