name: Cypress Tests

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4      
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run run-test
      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          command: npm run generate-report
      - name : my-artifact
        uses: actions/upload-artifact@v4
        with:
        name: my-artifact
          path: cypress/reports/html